# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\workingTimeSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 417)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(14)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(154, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 7, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 7, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 5), QtCore.QTime(15, 29, 0)))
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_2.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_2.setCalendarPopup(False)
        self.timeEdit_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_2.addWidget(self.timeEdit_2, 1, 1, 1, 1)
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_3.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_3.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_3.setCalendarPopup(False)
        self.timeEdit_3.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout_2.addWidget(self.timeEdit_3, 2, 1, 1, 1)
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_4.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_4.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_4.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_4.setCalendarPopup(False)
        self.timeEdit_4.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout_2.addWidget(self.timeEdit_4, 3, 1, 1, 1)
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_5.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_5.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_5.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_5.setCalendarPopup(False)
        self.timeEdit_5.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.gridLayout_2.addWidget(self.timeEdit_5, 4, 1, 1, 1)
        self.timeEdit_6 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_6.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_6.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_6.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_6.setCalendarPopup(False)
        self.timeEdit_6.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.gridLayout_2.addWidget(self.timeEdit_6, 5, 1, 1, 1)
        self.timeEdit_7 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_7.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_7.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_7.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_7.setCalendarPopup(False)
        self.timeEdit_7.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.gridLayout_2.addWidget(self.timeEdit_7, 6, 1, 1, 1)
        self.timeEdit_8 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_8.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_8.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_8.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_8.setCalendarPopup(False)
        self.timeEdit_8.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_8.setObjectName("timeEdit_8")
        self.gridLayout_2.addWidget(self.timeEdit_8, 7, 1, 1, 1)
        self.timeEdit_9 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_9.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_9.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_9.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_9.setCalendarPopup(False)
        self.timeEdit_9.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_9.setObjectName("timeEdit_9")
        self.gridLayout_2.addWidget(self.timeEdit_9, 0, 3, 1, 1)
        self.timeEdit_10 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_10.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_10.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_10.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_10.setCalendarPopup(False)
        self.timeEdit_10.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_10.setObjectName("timeEdit_10")
        self.gridLayout_2.addWidget(self.timeEdit_10, 1, 3, 1, 1)
        self.timeEdit_11 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_11.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_11.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_11.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_11.setCalendarPopup(False)
        self.timeEdit_11.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_11.setObjectName("timeEdit_11")
        self.gridLayout_2.addWidget(self.timeEdit_11, 2, 3, 1, 1)
        self.timeEdit_12 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_12.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_12.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_12.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_12.setCalendarPopup(False)
        self.timeEdit_12.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_12.setObjectName("timeEdit_12")
        self.gridLayout_2.addWidget(self.timeEdit_12, 3, 3, 1, 1)
        self.timeEdit_13 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_13.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_13.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_13.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_13.setCalendarPopup(False)
        self.timeEdit_13.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_13.setObjectName("timeEdit_13")
        self.gridLayout_2.addWidget(self.timeEdit_13, 4, 3, 1, 1)
        self.timeEdit_14 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_14.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_14.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_14.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_14.setCalendarPopup(False)
        self.timeEdit_14.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_14.setObjectName("timeEdit_14")
        self.gridLayout_2.addWidget(self.timeEdit_14, 5, 3, 1, 1)
        self.timeEdit_15 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_15.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_15.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_15.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_15.setCalendarPopup(False)
        self.timeEdit_15.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_15.setObjectName("timeEdit_15")
        self.gridLayout_2.addWidget(self.timeEdit_15, 6, 3, 1, 1)
        self.timeEdit_16 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_16.setMinimumSize(QtCore.QSize(110, 0))
        self.timeEdit_16.setMaximumSize(QtCore.QSize(110, 16777215))
        self.timeEdit_16.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit_16.setCalendarPopup(False)
        self.timeEdit_16.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_16.setObjectName("timeEdit_16")
        self.gridLayout_2.addWidget(self.timeEdit_16, 7, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 9, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "生产时段设置"))
        self.label.setText(_translate("Dialog", "当前部门："))
        self.label_6.setText(_translate("Dialog", "NOS1A"))
        self.label_18.setText(_translate("Dialog", "至"))
        self.label_4.setText(_translate("Dialog", "时段一："))
        self.label_9.setText(_translate("Dialog", "时段三："))
        self.label_15.setText(_translate("Dialog", "至"))
        self.label_3.setText(_translate("Dialog", "时段四："))
        self.label_16.setText(_translate("Dialog", "至"))
        self.label_17.setText(_translate("Dialog", "至"))
        self.label_2.setText(_translate("Dialog", "至"))
        self.label_13.setText(_translate("Dialog", "时段八："))
        self.label_14.setText(_translate("Dialog", "至"))
        self.label_10.setText(_translate("Dialog", "时段五："))
        self.label_11.setText(_translate("Dialog", "时段六："))
        self.label_19.setText(_translate("Dialog", "至"))
        self.label_5.setText(_translate("Dialog", "时段二："))
        self.label_12.setText(_translate("Dialog", "时段七："))
        self.timeEdit.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_2.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_3.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_4.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_5.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_6.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_7.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_8.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_9.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_10.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_11.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_12.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_13.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_14.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_15.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.timeEdit_16.setDisplayFormat(_translate("Dialog", "hh:mm"))
        self.label_7.setText(_translate("Dialog", "至"))
        self.pushButton.setText(_translate("Dialog", "保存设定"))
        self.pushButton_2.setText(_translate("Dialog", "关闭"))
